import RaceControllers from '../RaceControllers';
import './Garage.scss';
declare class Garage extends RaceControllers {
    private garage;
    private carsCounter;
    private createState;
    private updateState;
    private selectedCar;
    private page;
    private totalPages;
    private carlist;
    private garageInfo;
    private selectedCarInput;
    private winners;
    private animations;
    constructor();
    private generateGarage;
    private createGarageInfo;
    private createGarageControllers;
    private createCarInputs;
    private createControlInput;
    private createCarList;
    private getDistanceBetweenCarAndFinish;
    private resetState;
    private animateDriveCar;
    private animateStopCar;
    private saveWinner;
    private showWinner;
    onChange: (e: Event) => void;
    handleOpenGarage: () => Promise<void>;
    showWinners: () => void;
    createCar: () => Promise<void>;
    updateCar: () => Promise<void>;
    startRace: () => void;
    resetRace: () => Promise<void>;
    createCars: () => Promise<void>;
    selectCar: (id: number) => void;
    removeCar: (id: number) => Promise<void>;
    startCarEngine: (e: unknown, id: number) => Promise<void>;
    stopCar: (e: unknown, id: number) => Promise<void>;
    prevPage: () => void;
    nextPage: () => void;
    getSelectedInput(): void;
    disabledControllsButton(e: unknown, type: 'start' | 'stop'): void;
    getButtonByEvent(e: unknown): HTMLButtonElement;
}
declare const garage: Garage;
export default garage;
